package interpreter.fom.utils;

import interpreter.fom.model.FOMAttribute;
import interpreter.fom.model.FOMInteraction;
import interpreter.fom.model.FOMObjectClass;
import interpreter.fom.model.SharingType;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

public final class FOMContentUtils {

    private FOMContentUtils() {}

    /**
     * This Method generates the actual FOM for the given simulation object
     */
    public static String generateFOMString(List<FOMObjectClass> objectClasses, List<FOMInteraction> interactions, String filename) {
        String prettyIdentifier = filename.split("\\.")[0];

        // mergeFomAttributes(simulationObject);
        // mergeInteractions(simulationObject);

        String fomString = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n" +
                           // IEEE URLs were not reachable and were therefore replaced (17-11-2021)
                           // "<objectModel xsi:schemaLocation=\http://standards.ieee.org/downloads/1516/1516.2-2010/IEEE1516-DIF-2010.xsd\" xmlns=\"http://standards.ieee.org/IEEE1516-2010\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                           "<objectModel xmlns=\"https://www.sisostds.org/schemas/IEEE1516-2010\" xmlns:xsi=\"https://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"https://www.sisostds.org/schemas/IEEE1516-2010 https://www.sisostds.org/schemas/IEEE1516-DIF-2010.xsd\">\n" +
                           "    <modelIdentification>\n" +
                           "        <name>" + prettyIdentifier + "</name>\n" +
                           "        <type>FOM</type>\n" +
                           "        <version>4.0</version>\n" +
                           "        <modificationDate>" + LocalDate.now() + "</modificationDate>\n" +
                           "        <securityClassification>Unclassified</securityClassification>\n" +
                           "        <releaseRestriction>None</releaseRestriction>\n" +
                           "        <purpose>to define shared data for other federates</purpose>\n" +
                           "        <applicationDomain>Maritime Simulation</applicationDomain>\n" + // TODO get the domain 'name' from out of the scenario to keep this generic
                           "        <description>data contained in the class behaviours of class " + prettyIdentifier + "</description>\n" +
                           "        <useLimitation>derived models must reference this document</useLimitation>\n" +
                           "        <poc>\n" +
                           "            <pocType>Author</pocType>\n" + // TODO get author from scenario
                           "            <pocName>autogenerated by class Interpreter</pocName>\n" + // TODO include information about 'Model-based Distributed Traffic Simulation Environment' (MDTSEnv)
                           "            <pocOrg>PG MTSS</pocOrg>\n" + // TODO add university of oldenburg
                           "        </poc>\n" +
                           "    </modelIdentification>\n" +
                           "    <objects>\n" +
                           "        <objectClass>\n" +
                           "            <name>HLAobjectRoot</name>\n" +
                           "            " + FOMContentUtils.convertFOMObjectsToFomString(objectClasses) +
                           "        </objectClass>\n" +
                           "    </objects>\n" +
                           "    <dataTypes>\n" +
                           "    </dataTypes>\n" +
                           "   <interactions>\n" +
                           "       <interactionClass>" +
                           "           <name>HLAinteractionRoot</name>\n" +
                           "           " + FOMContentUtils.convertFOMInteractionsToFomString(interactions) +
                           "       </interactionClass>\n" +
                           "   </interactions>\n" +
                           "</objectModel>\n";

        return fomString;
    }

    /**
     * This method generates the interactions part of the fom
     * it therefore recursively iterates over the interactions using the fomPathToInteractionMap and the paths of the
     * interactions itself
     *
     * @param interactions
     * @return
     */
    public static String convertFOMInteractionsToFomString(List<FOMInteraction> interactions) {
        if (interactions == null) {
            return "";
        }

        if (interactions.isEmpty()) {
            return "";
        }
        StringBuilder fomString = new StringBuilder();
        for (FOMInteraction interaction : interactions) {

            String publishSubscribe = "";
            if (interaction.isPublish()) {
                publishSubscribe = publishSubscribe + "Publish";
            }
            if (interaction.isSubscribe()) {
                publishSubscribe = publishSubscribe + "Subscribe";
            }
            if (publishSubscribe.equals("")) {
                publishSubscribe = "Neither";
            }

            fomString.append("<interactionClass>\n")
                     .append("   <name>").append(interaction.getName()).append("</name>\n")
                     .append("   <sharing>").append(publishSubscribe).append("</sharing>\n")
                     .append("   <dimensions>")
                     .append(interaction.getDimensions()
                                        .stream()
                                        .map(d -> "<dimension>" +
                                                  d.getName() +
                                                  "</dimension>\n")
                                        .collect(Collectors.joining()))
                     .append("   </dimensions>\n ")
                     .append("   <transport>").append(interaction.getTransport()).append("</transport>\n")
                     .append("   <order>").append(interaction.getOrder()).append("</order>\n")
                     .append("   ").append(convertFOMInteractionsToFomString(interaction.getSubInteractions()))
                     .append("</interactionClass>\n");
        }
        return fomString.toString();
    }

    /**
     * This method generates the ObjectClass and Attribute Strings for the FOM
     *
     * @param fomObjectClass the objectClass that should be converted into a FOM String
     * @return the resulting String
     */
    public static String convertFOMObjectToFomString(FOMObjectClass fomObjectClass) {
        return convertFOMObjectsToFomString(List.of(fomObjectClass));
    }

    /**
     * This method generates the ObjectClass and Attribute Strings for the FOM
     * it therefore recursively iterates over the FomObjectClass Objects starting with the ObjectRoot
     *
     * @param fomObjectClasses the objectClasses that should be converted into a FOM String
     * @return the resulting String
     */
    public static String convertFOMObjectsToFomString(List<FOMObjectClass> fomObjectClasses) {
        if (fomObjectClasses == null) {
            return "";
        }
        if (fomObjectClasses.isEmpty()) {
            return "";
        }

        StringBuilder fomString = new StringBuilder();

        for (FOMObjectClass objectClass : fomObjectClasses) {
            fomString.append("<objectClass>\n")
                     .append("   <name>").append(objectClass.getName()).append("</name>\n")
                     .append("   <sharing>").append(objectClass.getSharingString()).append("</sharing>\n");

//        if (objectClass.getAttributes().size() > 0) {
//            forceAllClassAttributes(objectClass);
//        }
            for (FOMAttribute attribute : objectClass.getAttributes()) {
                fomString.append("   <attribute>\n")
                         .append("       <name>").append(attribute.getName()).append("</name>\n");

                // TODO put the publish subscribe strings into a constants providing service class or into an enum
                String publishSubscribe = "";
                if (attribute.isPublish()) {
                    publishSubscribe = publishSubscribe + SharingType.PUBLISH.toString();
                }
                if (publishSubscribe.equals("")) {
                    publishSubscribe = SharingType.NEITHER.toString();
                }

//            String dataType = simulationAttribute.getListType() != null ?
//                              dataTypeMap.get(simulationAttribute.getListType().getSimpleName()) :
//                              dataTypeMap.get(simulationAttribute.getDataType().substring(simulationAttribute.getDataType().lastIndexOf(".") + 1));

                fomString.append("       <dataType>").append(attribute.getDataType()).append("</dataType>\n")
                         .append("       <updateType>").append(attribute.getUpdateType()).append("</updateType>\n")
                         .append("       <ownership>").append(attribute.getOwnerShip()).append("</ownership>\n")
                         .append("       <sharing>").append(publishSubscribe).append("</sharing>\n")
                         .append("   </attribute>\n");
            }
            fomString.append("   ").append(convertFOMObjectsToFomString(objectClass.getSubClasses()))
                     .append("</objectClass>\n");
        }
        return fomString.toString();
    }

}
